apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mqttlegacyorch.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.mqttlegacyorch.name }}
    group: {{ .Values.app.group }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.mqttlegacyorch.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mqttlegacyorch.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mqttlegacyorch.name }}
    spec:
      containers:
      - name: {{ .Values.mqttlegacyorch.name }}
        image: {{ .Values.mqttlegacyorch.container.image }}
        imagePullPolicy: {{ .Values.app.imagePullPolicy }}
        resources:
          limits:
            memory: {{ .Values.mqttlegacyorch.container.memory }}
            cpu: {{ .Values.mqttlegacyorch.container.cpu }}
        env:
        - name: MB_ADMIN_EMAIL
          value: isaacob@ucar.edu
        - name: MB_ADMIN_PASS
          value: "@siparcs25"
        - name: MB_DB_TYPE
          value: postgres
        - name: MB_DB_DBNAME
          value: metabase
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_USER
          value: postgres
        - name: MB_DB_PASS
          value: temppostgrespw
        - name: MB_DB_HOST
          value: postgres
        - name: ORCH_DB_USER
          value: postgres
        - name: ORCH_DB_PASS
          value: temppostgrespw
        - name: ORCH_DB_NAME
          value: iotwx_db
        - name: ORCH_DB_HOST
          value: postgres
        volumeMounts:
        - name: config-volume
          mountPath: /cloud/config.yaml
          subPath: config.yaml
        - name: logger-volume
          mountPath: /cloud/services/mqtt_legacy/logger.py
          subPath: logger.py
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.app.config.name }}
      - name: logger-volume
        configMap:
            name: {{ .Values.app.logger.name }}